name: Aliyun Signin

on:
  schedule:
   # 每天国际时间 17:20 运行一次, 中国时间 01:20
    - cron: '20 23 * * *'
  workflow_dispatch:
jobs:
  signin:
    name: Aliyun Signin
    runs-on: ubuntu-latest
    steps:
      - uses: ImYrS/aliyun-auto-signin@main
        with:
          REFRESH_TOKENS: 1fce4a2284a04f48a9067ea6cece0760
          GP_TOKEN: ${{ secrets.GP_TOKEN}}
          PUSH_TYPES: 'TELEGRAM'
          TELEGRAM_BOT_TOKEN: 6036055864:AAHrJbijxeN5uwLvR5FXEQK9KtuQYZ3Ocac
          TELEGRAM_CHAT_ID: 5003082910
